apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0sga
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nxjj-tenant/rhtap-demo-app/hacbs-test-project-0sga@sha256:11d1027920b2107a7d29683515801c38b2c3de4c5b5e58f852be94da4d7cce6d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
